# Generated by Django 2.1.5 on 2019-01-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='relators',
            new_name='realtor',
        ),
    ]
